[package]
name = "storage-vevt"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
# Use workspace path dependency
shnn-storage = { path = "../../crates/shnn-storage" }